name: API Testing with Postman

on:
  push:
    branches:
      - main  # Runs tests when code is pushed to 'main'
  pull_request:
    branches:
      - main  # Runs tests on PRs to 'main'

jobs:
  postman_tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Use latest stable version

      - name: Install Newman
        run: npm install -g newman newman-reporter-html

      - name: Run Postman Collection
        run: newman run Demoapi.json --reporter-html-export newman-report.html

      - name: Upload Test Report
        uses: actions/upload-artifact@v3
        with:
          name: Postman Test Report
          path: newman-report.html
